# 🏷️ Auto Labeler Configuration
# 這個檔案會自動為 PR 添加標籤，基於分支名稱和檔案變更路徑
# 設計來支援 Golang 專案（亦相容部分前端檔案），與 release-drafter.yml 完全對應

# 主要標籤會被 release-drafter.yml 用於：
# 1. 自動分類到對應的 changelog 區段
# 2. 決定版本號 (Major/Minor/Patch)
# 3. 生成 release notes

# ===============================
# 🎯 Main Labels (對應 release-drafter categories)
# ===============================

# 💥 Breaking Changes
breaking:
  - head-branch:
      - "^breaking/.*"
      - "^major/.*"
      - "^BREAKING/.*"

# ✨ Features
feature:
  - head-branch:
      - "^feat/.*"
      - "^feature/.*"
      - "^add/.*"
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.go"
          - "cmd/**"
          - "internal/**"
          - "pkg/**"

# 🐛 Bug Fixes
bugfix:
  - head-branch:
      - "^fix/.*"
      - "^bug/.*"
      - "^bugfix/.*"
      - "^hotfix/.*"

# 🧰 Maintenance
chore:
  - head-branch:
      - "^chore/.*"
      - "^maintenance/.*"
      - "^config/.*"
      - "^update/.*"
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".golangci.yml"
          - "go.mod"
          - "go.sum"
          - "Makefile"
          - ".editorconfig"

# 📦 Dependencies
dependencies:
  - head-branch:
      - "^dep/.*"
      - "^deps/.*"
      - "^dependencies/.*"
      - "^dependabot/.*"
  - changed-files:
      - any-glob-to-any-file:
          - "go.mod"
          - "go.sum"
          - "docker/**/Dockerfile"
          - ".devcontainer/**"
          - "package.json"
          - "package-lock.json"
          - "yarn.lock"
          - "pnpm-lock.yaml"

# 📝 Documentation
documentation:
  - head-branch:
      - "^docs/.*"
      - "^doc/.*"
      - "^documentation/.*"
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "**/*.md"
          - "**/*.rst"
          - "**/*.ipynb"
          - "notebooks/**/*"
          - "notebook/**/*"
          - "mkdocs.yml"
          - "README*"
          - "CHANGELOG*"

# 🧪 Tests
unit-test:
  - head-branch:
      - "^test/.*"
      - "^tests/.*"
  - changed-files:
      - any-glob-to-any-file:
          - "**/*_test.go"
          - "jest.config.*"
          - "vitest.config.*"

# ⚡️ Performance Improvements
perf:
  - head-branch:
      - "^perf/.*"
      - "^performance/.*"
      - "^optimize/.*"
  - changed-files:
      - any-glob-to-any-file:
          - "**/*perf*.py"
          - "**/*benchmark*.py"
          - "**/*performance*.py"
          - "**/*perf*.ts"
          - "**/*benchmark*.ts"
          - "**/*performance*.ts"

# 🔒️ Security Fixes
security:
  - head-branch:
      - "^security/.*"
      - "^sec/.*"
  - changed-files:
      - any-glob-to-any-file:
          - "**/*security*.py"
          - "**/*auth*.py"
          - "**/*credential*.py"
          - "**/*security*.ts"
          - "**/*auth*.ts"
          - "**/*credential*.ts"

# ♻️ Code Refactoring
refactor:
  - head-branch:
      - "^refactor/.*"
      - "^cleanup/.*"
      - "^restructure/.*"

# 🎨 Code Style & Formatting
style:
  - head-branch:
      - "^style/.*"
      - "^format/.*"
      - "^lint/.*"
  - changed-files:
      - any-glob-to-any-file:
          - ".golangci.yml"
          - ".eslintrc*"
          - ".prettier*"
          - "stylelint*"
          - "**/*.css"
          - "**/*.scss"
          - "**/*.sass"

# 🔙 Reverts
revert:
  - head-branch:
      - "^revert/.*"
      - "^rollback/.*"
