name: Tests

on:
  push:
    branches:
      - main
      - master
      - release/*
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
      - master
      - release/*
    paths-ignore:
      - "**/*.md"

permissions: write-all

jobs:
  run_tests:
    if: ${{ !(startsWith(github.head_ref, 'chore/') || startsWith(github.head_ref, 'ci/') || startsWith(github.head_ref, 'docs/')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test
        run: |
          make test
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            coverage.html
